kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  environment:
    TOKEN:
      from_secret: dockerhub_token
  settings:
    repo: rappet/rappetxyz
    auto_tag: true
    build_args_from_env:
      - TOKEN
