baseURL = "https://rappet.xyz/"
languageCode = "en-us"
title = "rappet's Blog"
theme = "hello-friend-ng"
paginate = 10

[params]
	dateform = "Jan 2, 2006"
	dateformShort = "Jan 2"
	dateformNum = "2006-02-01"
	dateformNumTime = "2006-02-01T15:04 +0200"

	homeSubtitle = "My thoughs"
	# Metadata mostly used in document's head
  description = "rappet's thoughs"
  keywords = "blog, rappet"
  images = [""]

	defaultTheme = "light"

	[[params.social]]
		name = "twitter"
		url = "https://twitter.com"

	[[params.social]]
		name = "email"
		url = "mailto:raphael.r.peters@gmail.com"

	[[params.social]]
		name = "github"
		url = "https://github.com/rappet"

#  [[params.social]]
#    name = "gitlab"
#    url = "https://gitlab.com/rappet"

  [[params.social]]
    name = "dev"
    url = "https://git.rappet.xyz/rappet"

[taxonomies]
	category = "blog"
	tag      = "tags"
	series   = "series"

[languages]
	[languages.en]
		title = "rappet's blog"
		subtitle = "my thoughs"
		keywords = ""
		copyright = '(c) Raphael Peters 2020'
		readOtherPosts = "Read other posts"

		[languages.en.params.logo]
			logoText = "rappet's blog"
			logoHomeLink = "/"

[[menu.main]]
	identifier = "blog"
	name       = "Blog"
	url        = "/posts"
